version: '3.8'

services:
  web:
    build: .
    command: rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - db
      - elasticsearch
      - redis
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  # Ensure Rails app knows where Elasticsearch is

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "NewSecurePassword"
      MYSQL_DATABASE: myapp_development
    ports:
      - "3306:3306"  # Adjusted port to avoid conflict with local MySQL
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
      

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for development
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data  # Persist Elasticsearch data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  db_data:
    driver: local
  esdata1:
    driver: local
